### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JohnPaulQiangChen** [LCOGT/alipy#1]
The example line  
`  identifications = make_transforms(ref_image, images_to_align)`

I got 

`Traceback (most recent call last):
  File "fits_align_test.py", line 32, in <module>
    identifications = make_transforms(ref_image, images_to_align)
  File "/home/chen/python-chen/chen3.6/lib/python3.6/site-packages/fits_align/ident.py", line 194, in make_transforms
    ref.makecat()
  File "/home/chen/python-chen/chen3.6/lib/python3.6/site-packages/fits_align/imgcat.py", line 70, in makecat
    self.cat = hdu[2].data
  File "/home/chen/python-chen/chen3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 318, in __getitem__
    raise e
  File "/home/chen/python-chen/chen3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 314, in __getitem__
    self._positive_index_of(key))
  File "/home/chen/python-chen/chen3.6/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1111, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range
`

**Comment by a-sani** [comment]
Hi, I seem to be getting the same error running the `make_transforms()` method. I believe issue lives with the `imgcat.py` file on line 70 in makecat. The `hdu[2].data` does not exist, the list value of hdu should be 0: `hdu[0].data` .

**Comment by Amararyan** [comment]
I also had a similar error showing "IndexError: list index out of range". Further,I tried the solution as suggested by a-sani and changed hdu[2].data to hdu[0].data on line 70 in imgcat.py file. But, then when I ran the code again, I got the  "AttributeError: 'numpy.ndarray' object has no attribute 'columns'". What could be the possible solution? Please suggest.

**Comment by zemogle** [comment]
You're absolutely right. I'm sorry I didn't see this issue before. I had this issue today. I mistakenly hardcoded the header ID for the catalogue. I now allow you to pass this into `make_transforms()`. I have set the default to be `hdu='CAT'` which is a more helpful default. I've tagged this release as `0.4.4` and it will appear on PyPi soon.
